export const defaultTypeEs = {
	normal: 'Normal',
	fighting: 'Lucha',
	flying: 'Volador',
	poison: 'Veneno',
	ground: 'Tierra',
	rock: 'Roca',
	bug: 'Bicho',
	ghost: 'Fantasma',
	steel: 'Acero',
	fire: 'Fuego',
	water: 'Agua',
	grass: 'Planta',
	electric: 'Eléctrico',
	psychic: 'Psíquico',
	ice: 'Hielo',
	dragon: 'Dragón',
	dark: 'Siniestro',
	fairy: 'Hada',
	unknown: 'Desconocido',
	shadow: 'Sombra',
};

export const defaultMovesEs = {
	'razor-wind': 'Viento Cortante',
	'swords-dance': 'Danza Espada',
	cut: 'Corte',
	gust: 'Tornado',
	'wing-attack': 'Ataque Ala',
	whirlwind: 'Remolino',
	fly: 'Vuelo',
	'binding-voice': 'Voz Cautivadora',
	'leech-life': 'Absorber',
	'poison-sting': 'Picotazo Veneno',
	twineedle: 'Doble Filo',
	'pin-missile': 'Misil Pincho',
	leer: 'Gruñido',
	bite: 'Mordisco',
	growl: 'Rugido',
	roar: 'Rugido',
	sing: 'Canto',
	supersonic: 'Supersónico',
	sonicboom: 'Rayo Sonic',
	disable: 'Desactivar',
	acid: 'Ácido',
	ember: 'Ascuas',
	flamethrower: 'Lanzallamas',
	mist: 'Niebla',
	'water-gun': 'Pistola Agua',
	'hydro-pump': 'Hidrobomba',
	surf: 'Surf',
	'ice-punch': 'Puño Hielo',
	blizzard: 'Ventisca',
	psybeam: 'Psicorrayo',
	'psycho-cut': 'Psicocorte',
	'psycho-shift': 'Psicotransmisión',
	'thunder-shock': 'Impactrueno',
	thunderbolt: 'Rayo',
	'vine-whip': 'Látigo Cepa',
	bind: 'Atadura',
	'razor-leaf': 'Hoja Afilada',
	'poison-powder': 'Polvo Veneno',
	'sleep-powder': 'Polvo Somnífero',
	'stun-spore': 'Paralizador',
	'string-shot': 'Hilo Viscoso',
	'dragon-breath': 'Aliento Dragón',
	'dragon-claw': 'Garra Dragón',
	'dragon-dance': 'Danza Dragón',
	'dragon-rush': 'Furia Dragón',
};
